# Generated by Django 5.0.3 on 2024-03-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='account',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
