# Generated by Django 5.0.3 on 2024-03-19 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_userconfig_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='server',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='account',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
