# Generated by Django 5.0.3 on 2024-03-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_userconfig_server_alter_userconfig_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='account',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
