# Generated by Django 5.0.3 on 2024-03-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_userconfig_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
    ]
